# Analysis options for Awakeia project
# This file configures the static analysis tool for Dart and Flutter code

# Include recommended Flutter lints
include: package:flutter_lints/flutter.yaml

# Linter rules configuration
linter:
  rules:
    # Performance rules
    - avoid_unnecessary_containers
    - avoid_function_literals_in_foreach_calls
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - sized_box_for_whitespace
    - use_key_in_widget_constructors

    # Code style rules
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first

    # Safety rules
    - avoid_print
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - use_build_context_synchronously

    # Naming conventions
    - file_names
    - package_names
    - library_names
    - non_constant_identifier_names
    - constant_identifier_names

    # Widget best practices
    - avoid_returning_null_for_void
    - prefer_if_null_operators
    - prefer_null_aware_operators
    - unnecessary_null_aware_assignments
    - unnecessary_parenthesis

    # Import organization
    - directives_ordering
    - prefer_relative_imports

    # Additional Flutter-specific rules
    - use_colored_box
    - use_decorated_box

# Analyzer configuration
analyzer:
  # Exclude generated files from analysis
  exclude:
    - "**/*.g.dart"           # Generated files (json_serializable, etc.)
    - "**/*.freezed.dart"     # Freezed generated files
    - "**/generated/**"       # Generated localization files
    - "build/**"              # Build output
    - ".dart_tool/**"         # Dart tool cache

  # Language settings
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  # Enable additional checks
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  # Error handling
  errors:
    # Treat specific warnings as errors for critical issues
    invalid_assignment: error
    invalid_use_of_protected_member: error
    missing_required_param: error
    undefined_class: error
    undefined_function: error
    undefined_method: error

    # Keep some as warnings to not be too strict
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning

# Plugin configuration
plugins:
# Add any analyzer plugins here if needed
# - angular
# - json_schema