name: awakeia
description: "Tracker for your sleep and wake-up habits"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.3.0

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets - append images and other assets here later
  # assets:
  #   - images/

  # Fonts - append custom fonts here later
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont.ttf